<?php
// Words that are reserved in javascript.
// - delete
// - new
// Please, use the following format i18n('save') not i18n.save
// JavaScript has reserved variables after the dot.
$LANG = array(

	// This items are used internally by the GaiaEHR Application.
	'id_ID'									=> 'Indonesia',
	'i18nExtFile'							=> 'ext-lang-en.js',
    'description'							=> 'Keterangan',
    'code'									=> 'Kode',
    'dashboard'         					=> 'Papan Instrumen',
    'form'                                  => 'Form',
    'administration'						=> 'Administrasi',
    'global_settings'						=> 'Setting Umum',
    'jenis' 	        					=> 'Jenis',
    'company'	          					=> 'Perusahaan',
    'bentuk'								=> 'Bentuk',
    'bahanbaku'								=> 'Bahan Baku',
    'kemasan'								=> 'Kemasan',
    'jenis'									=> 'Jenis',
    'satuan'								=> 'Satuan',
    'spesifikasi'							=> 'Spesifikasi',
    'customer'								=> 'Pelanggan',
    'vendor'	          					=> 'Supplier',
    'items'			    					=> 'Produk',
    'formula'			       				=> 'Resep',
    'transaksi'			       				=> 'Transaksi',
    'salesorder'		       				=> 'Pesanan Penjualan',
    'master_manager'						=> 'Master',
	'miscellaneous'							=> 'Lain-lain',
	'my_account'							=> 'Akun saya',
	'users'									=> 'Pengguna',
    'save_configuration'					=> 'Simpan Konfigurasi',
    'main_top_pane_screen'					=> 'Tampilan Utama',
    'layout_style'							=> 'Layout style',
    'theme'									=> 'Theme',
    'navigation_area_width'					=> 'Navigation area width',
    'fullname_format'						=> 'Fullname format',
    'default_language'						=> 'Default language',
    'date_display_format'					=> 'Date Display Format',
    'time_display_format'					=> 'Time Display Format',
    'currency_decimal_places'				=> 'Currency Decimal Places',
    'currency_decimal_point_symbol'			=> 'Currency Decimal Point Symbol',
    'currency_thousands_separator'			=> 'Currency Thousands Separator',
    'currency_designator'					=> 'Currency Designator',
    'autosave_forms'						=> 'Autosave forms',
    'idle_session_timeout_seconds'			=> 'Idle session timeout in seconds',
    'new_global_configuration_saved'		=> 'New global configuration saved',
    'refresh_the_application'				=> 'Refresh the application',
    'last_first_middle'						=> 'Last, First',
    'first_middle_last'						=> 'First Last',
    'main_navigation_menu_left'				=> 'Main Navigation Menu (left)',
    'main_navigation_menu_right'			=> 'Main Navigation Menu (right)',
    'grey_default'							=> 'Grey (default)',
    'blue'									=> 'Blue',
    'access'								=> 'Access',
    'yyyy_mm_dd'							=> 'YYYY-MM-DD',
    'mm_dd_yyyy'							=> 'MM/DD/YYYY',
    'dd_mm_yyyy'							=> 'DD/MM/YYYY',
    '24_hr'									=> '24 hr',
    '12_hr'									=> '12 hr',
    '0'										=> '0',
    '1'										=> '1',
    '2'										=> '2',
    'comma'									=> 'Comma',
    'period'								=> 'Period',
    'space'									=> 'Space',
    'none'									=> 'None',
    'text_field'							=> 'Text field',
    'single_selection_list'					=> 'Single-selection list',
    'appearance'							=> 'Appearance',
    'loading'								=> 'Loading',
    'loading...'						    => 'Loading...',
    'authorized'							=> 'Authorized?',
    'edit_user'								=> 'Edit User',
    'add_new_user'							=> 'Add New User',
    'username'								=> 'Username',
    'password'								=> 'Kata Sandi',
    'name'									=> 'Nama',
    'active?'								=> 'Aktif?',
    'active'								=> 'Aktif',
    'add_new'								=> 'Tambah Baru',
    'create'								=> 'Buat',
    'save'									=> 'Simpan',
    'cancel'								=> 'Batal',
    'personal_info'                         => 'Pribadi Info',
    'login_info'                            => 'Login Info',
    'other_info'                            => 'Informasi Lain',
    'change_password'                       => 'Ganti Kata Sandi',
    'change_you_password'                   => 'Ganti Kata Sandi anda',
    'old_password'                          => 'Kata Sandi Lama',
    'new_password'                          => 'Kata Sandi Baru',
    're_type_password'                      => 'Ketik ulang kata sandi',
    'page'                                  => 'Halaman',
    'update'                                => 'Ubah',
    'salesman'                              => 'Penjual',
    'wilayah'                               => 'Wilayah',
    'purchaseorder'                         => 'Pembelian',
    'goodsreceived'                         => 'Penerimaan Barang',
    'goodsissued'                           => 'Pengiriman Barang',
    'workorder'                             => 'Produksi'

);
